Repository Codeit-Part3-Team3/Taskify, pull requests merged in 2023-12, with the labels that each got.

#3 [#2] ISSUE 템플릿 수정
  .github/ISSUE_TEMPLATE/refator.yml
  .github/ISSUE_TEMPLATE/✅-feature.md
  .github/ISSUE_TEMPLATE/❌-bug.md
Labels: Chore

#12 [#6] Git Action CI 설정
  .github/workflows/main.yml
  src/app/(afterLogin)/[username]/page.tsx
  src/app/(beforeLogin)/login/page.tsx
Labels: Chore

#11 [#10]: PR Template 생성
  pull_request_template.md
Labels: Chore

#13 [#9] issue 템플릿 기능 추가
  .github/ISSUE_TEMPLATE/chore.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/ISSUE_TEMPLATE/style.yml
Labels: Chore

#15 [#5] 글꼴 적용
  src/app/globals.css
  src/app/layout.tsx
  tailwind.config.ts
Labels: Chore

#20 [#16]: auto-assign 생성
  .github/auto_assign.yml
Labels: Chore

#18 [#7] Chore : 이미지 파일 추가
  public/icons/add_box_icon.svg
  public/icons/add_icon.svg
  public/icons/add_icon_large.svg
  public/icons/arrow_drop_down_icon.svg
  public/icons/arrow_forward_icon.svg
  public/icons/banner_logo_icon_20.svg
  public/icons/banner_logo_icon_24.svg
  public/icons/banner_logo_icon_34.svg
  public/icons/banner_logo_icon_40.svg
  public/icons/calendar_icon.svg
  public/icons/close_icon.svg
  public/icons/crown_icon.svg
  public/icons/done_icon.svg
  public/icons/email_icon.svg
  public/icons/facebook_icon.svg
  public/icons/instagram_logo.svg
  public/icons/more_icon.svg
  public/icons/search_icon.svg
  public/icons/settings_icon.svg
  public/icons/unsubscribe_icon.svg
  public/icons/visibility_off_icon.svg
  public/icons/visibility_on_icon.svg
  public/images/hero.png
  public/images/landing1.png
  public/images/landing2.png
  public/images/landing3.png
  public/images/landing4.png
  public/images/landing5.png
  public/logo/logo_large.png
  public/logo/logo_small.png
  public/logo/nav_lgoo_small.svg
  public/logo/nav_logo_large.svg
Labels: Chore

#37 [#36] 이미지 파일 및 이슈 템플릿 오타 수정
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/ISSUE_TEMPLATE/style.yml
  public/images/hero.png
  public/images/landing1.png
  public/images/landing2.png
  public/images/landing3.png
  public/images/landing4.png
  public/images/landing5.png
Labels: Chore

#29 [#23] 랜딩페이지
  public/icons/email_icon.svg
  public/icons/facebook_icon.svg
  public/icons/icons8-github.svg
  public/icons/icons8-notion.svg
  public/icons/instagram_logo.svg
  src/app/(beforeLogin)/_component/Card.tsx
  src/app/(beforeLogin)/_constants/landing.ts
  src/app/(beforeLogin)/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
Labels: Feat

#38 [#26] Chip Components 구현
  public/icons/check_color.svg
  public/icons/status_ellipse.svg
  src/app/_component/Chip/Add/index.tsx
  src/app/_component/Chip/Number/index.tsx
  src/app/_component/Chip/SelectColor/index.tsx
  src/app/_component/Chip/Status/index.tsx
  src/app/_component/Chip/Tag/index.tsx
  src/app/_constant/Chip.ts
  src/app/globals.css
  tailwind.config.ts
Labels: Feat

#41 [#27] Button Component 구현
  src/app/_component/Button/Cancel/index.tsx
  src/app/_component/Button/Corfirm/index.tsx
  src/app/_component/Button/Input/index.tsx
Labels: Feat

#30 [#24] 사이드 메뉴
  .github/pull_request_template.md
  public/images/add_box_icon.svg
  public/images/crown_icon.svg
  public/images/eclipse_small_icon_green.svg
  public/images/eclipse_small_icon_pink.png
  public/images/eclipse_small_icon_purple.svg
  public/images/eclipse_small_icon_skyblue.svg
  public/images/eclipse_small_icon_yellow.svg
  public/logo/logo_text_only.svg
  public/logo/nav_logo_small.svg
  src/app/(afterLogin)/_component/IdxIcon.tsx
  src/app/(afterLogin)/_component/SideMenu.tsx
  src/app/(beforeLogin)/page.tsx
  src/app/_util/axiosInstance.tsx
Labels: Feat

#44 [#25] Input 컴포넌트 구현
  package-lock.json
  package.json
  public/icons/calendar_icon.svg
  src/app/_component/Input/InputField.tsx
  src/app/_component/Input/icons/CalendarIcon.tsx
  src/app/_component/Input/icons/CloseIcon.tsx
  src/app/_component/Input/icons/EyeOffIcon.tsx
  src/app/_component/Input/icons/EyeOnIcon.tsx
Labels: Feat

#48 [#40] 대시보드 헤더 프로필 이미지
  .github/pull_request_template.md
  public/fonts/Montserrat-SemiBold.ttf
  public/next.svg
  public/vercel.svg
  src/app/(afterLogin)/_component/ProfileImg.tsx
  src/app/(afterLogin)/_component/ProfileImgCollection.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: Feat

#56 [#50] 공통 Button 컴포넌트 구현
  public/icons/arrow_backward_icon.svg
  public/icons/disabled_arrow_backward_icon.svg
  public/icons/disabled_arrow_forward_icon.svg
  src/app/_component/Button/AcceptReject/index.tsx
  src/app/_component/Button/AddColumn/index.tsx
  src/app/_component/Button/AddDashboard/index.tsx
  src/app/_component/Button/AddTodo/index.tsx
  src/app/_component/Button/CardDashboard/index.tsx
  src/app/_component/Button/Delete/index.tsx
  src/app/_component/Button/DeleteDashboard/index.tsx
  src/app/_component/Button/PageNation/index.tsx
  src/app/_component/Button/Sign/index.tsx
Labels: Feat

#53 [#45] 카드, 카드 리스트 컴포넌트 구현
  src/app/(afterLogin)/_component/Card/index.tsx
  src/app/(afterLogin)/_component/CardList/index.tsx
Labels: Feat

#58 [#49] 이미지 삽입
  public/icons/pen.svg
  src/app/(afterLogin)/_component/AddImageFile/index.tsx
  src/app/globals.css
Labels: Feat

#62 [#47] 공유 컴포넌트-초대받은 대시보드-테이블
  public/images/magifying_glass_icon.svg
  public/images/no_invitation_icon.svg
  src/app/(afterLogin)/[username]/page.tsx
  src/app/(afterLogin)/_component/Header/index.tsx
  src/app/(afterLogin)/_component/Icons/IdxIcon.tsx
  src/app/(afterLogin)/_component/Icons/MagnifyingGlass.tsx
  src/app/(afterLogin)/_component/Icons/NoInvitationIcon.tsx
  src/app/(afterLogin)/_component/InvitationDashboard/DummyData.tsx
  src/app/(afterLogin)/_component/InvitationDashboard/InvitationList.tsx
  src/app/(afterLogin)/_component/InvitationDashboard/NoInvitation.tsx
  src/app/(afterLogin)/_component/InvitationDashboard/index.tsx
  src/app/(afterLogin)/_component/SideMenu/index.tsx
  src/app/(afterLogin)/dashboard/page.tsx
  src/app/(afterLogin)/mydashboard/page.tsx
Labels: Feat

#64 [#54] 대시보드 페이지 구현
  src/app/(afterLogin)/_component/Card/index.tsx
  src/app/(afterLogin)/_component/CardList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/page.tsx
  src/app/(afterLogin)/layout.tsx
  src/app/(afterLogin)/laytout.tsx
  src/app/(beforeLogin)/laytout.tsx
  src/app/_component/Button/AddColumn/index.tsx
  src/app/_component/Button/AddTodo/index.tsx
Labels: Feat

#68 [#51]: 모달 컴포넌트 구현
  public/icons/crown_icon.svg
  public/icons/instagram_logo.svg
  public/icons/kebab.svg
  public/icons/line.svg
  public/images/crown_icon.svg
  public/logo/nav_logo_small.svg
  src/app/(afterLogin)/laytout.tsx
  src/app/_component/Button/Cancel/index.tsx
  src/app/_component/Button/Corfirm/index.tsx
  src/app/_component/Icons/Crown.tsx
  src/app/_component/Input/DropdownAndFilter.tsx
  src/app/_component/Input/InputField.tsx
  src/app/_component/modal/ModalLayout.tsx
  src/app/_component/modal/column/index.tsx
  src/app/_component/modal/dashBoard/index.tsx
  src/app/_component/modal/index.tsx
  src/app/_component/modal/sign/index.tsx
  src/app/_component/modal/toDoCard/DetailComponent.tsx
  src/app/_component/modal/toDoCard/index.tsx
  src/app/_component/modal/wrongPW/index.tsx
  src/app/_constant/modalType.tsx
  src/app/_hook/useRenderModal.tsx
  src/app/_util/returnModal.tsx
  src/app/layout.tsx
Labels: Feat

#71 [#70] : Auto Assign 설정 변경
  .github/auto_assign.yml
Labels: Chore

#69 [#57] 대시보드 수정페이지 구현
  public/icons/add_box.svg
  src/app/(afterLogin)/_component/DefaultProfile/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/EditBoard/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/InviteList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/MemberList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/page.tsx
  src/app/_component/Button/CancelInvite/index.tsx
  src/app/_component/Button/Confirm/index.tsx
  src/app/_component/Button/DeleteDashboard/index.tsx
  src/app/_component/Chip/SelectColor/index.tsx
  src/app/_component/DefaultProfile/index.tsx
  src/app/_component/modal/ModalLayout.tsx
  src/app/_hook/useGetWindowSize.ts
Labels: Feat

#79 [#67] 인풋 컴포넌트에 react-hook-form 적용
  package-lock.json
  package.json
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/EditBoard/index.tsx
  src/app/_component/Button/Cancel/index.tsx
  src/app/_component/Icons/CalendarIcon.tsx
  src/app/_component/Icons/CloseIcon.tsx
  src/app/_component/Icons/EyeOffIcon.tsx
  src/app/_component/Icons/EyeOnIcon.tsx
  src/app/_component/Input/DropdownAndFilter.tsx
  src/app/_component/Input/InputField.tsx
  src/app/_component/InputForm/CommentInput.tsx
  src/app/_component/InputForm/DateInput.tsx
  src/app/_component/InputForm/EmailInput.tsx
  src/app/_component/InputForm/InputStyle.tsx
  src/app/_component/InputForm/PasswordCheck.tsx
  src/app/_component/InputForm/PasswrdInput.tsx
  src/app/_component/InputForm/TagInput.tsx
  src/app/_component/InputForm/TextInput.tsx
  src/app/_component/InputForm/index.tsx
  src/app/_component/modal/ModalLayout.tsx
  src/app/_component/modal/column/index.tsx
  src/app/_component/modal/dashBoard/index.tsx
  src/app/_component/modal/index.tsx
  src/app/_component/modal/toDoCard/index.tsx
  src/app/_constant/Input.ts
  src/app/_hook/useRenderModal.tsx
  src/app/_util/returnModal.tsx
Labels: Feat

#78 [#74] 공통 Button 컴포넌트 free Size 스타일 추가
  src/app/_component/Button/AcceptReject/index.tsx
  src/app/_component/Button/AddColumn/index.tsx
  src/app/_component/Button/AddDashboard/index.tsx
  src/app/_component/Button/AddTodo/index.tsx
  src/app/_component/Button/Cancel/index.tsx
  src/app/_component/Button/CardDashboard/index.tsx
  src/app/_component/Button/Confirm/index.tsx
  src/app/_component/Button/Delete/index.tsx
  src/app/_component/Button/DeleteDashboard/index.tsx
  src/app/_component/Button/Input/index.tsx
  src/app/_component/Button/PageNation/index.tsx
  src/app/_component/Button/Sign/index.tsx
Labels: Style

#72 [#66] Signup, login 페이지 레이아웃 구현
  package-lock.json
  public/images/custom-checkbox-icon.svg
  src/app/(beforeLogin)/_component/Auth/AuthLayout.tsx
  src/app/(beforeLogin)/_component/Icons/Checkbox.tsx
  src/app/(beforeLogin)/_component/Icons/ImageLogo.tsx
  src/app/(beforeLogin)/_component/Icons/TextLogo.tsx
  src/app/(beforeLogin)/_constants/auth.ts
  src/app/(beforeLogin)/login/page.tsx
  src/app/(beforeLogin)/signup/page.tsx
  src/app/_component/Button/Sign/index.tsx
  src/app/_component/Input/InputField.tsx
  tailwind.config.ts
Labels: Feat

#82 [#65] 헤더 Api 연결
  src/app/(afterLogin)/_component/ProfileImgCollection.tsx
  src/app/(afterLogin)/_component/ProfileImgCollection/ProfileImg.tsx
  src/app/(afterLogin)/_component/ProfileImgCollection/index.tsx
  src/app/(afterLogin)/_constant/type.ts
  src/app/(afterLogin)/_util/useGetMembers.ts
  src/app/_util/useAsync.ts
Labels: Feat

#76 [#61] 나의 대시보드 페이지 구현
  src/app/(afterLogin)/_component/DashboardList/index.tsx
  src/app/(afterLogin)/mydashboard/page.tsx
  src/app/_component/Button/CardDashboard/index.tsx
Labels: Feat

#81 [#80] 대시보드 수정페이지 헤더,사이드바 적용 CSS 수정
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/EditBoard/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/InviteList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/MemberList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/page.tsx
Labels: Style

#96 [#86] 나의 대시보드 API 연결 및 리코일 적용
  src/app/(afterLogin)/_api/dashboard.ts
  src/app/(afterLogin)/_component/Card/index.tsx
  src/app/(afterLogin)/_component/DashboardList/index.tsx
  src/app/(afterLogin)/_component/SideMenu/index.tsx
  src/app/(afterLogin)/_constant/Dashboard.ts
  src/app/(afterLogin)/myboard/page.tsx
  src/app/(afterLogin)/mydashboard/page.tsx
  src/app/_component/Button/CardDashboard/index.tsx
  src/app/_recoil/dashboardAtoms.ts
  src/app/_recoil/recoilContextProvider.tsx
  src/app/layout.tsx
Labels: Feat

#95 [#75] 대시보드 수정페이지 페이지네이션
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/EditBoard/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/InviteList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/MemberList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/page.tsx
  src/app/_api/Dashboards/index.ts
Labels: Feat

#101 [#83] 초대하기, 초대목록 불러오기
  src/app/(afterLogin)/_component/Header/index.tsx
  src/app/(afterLogin)/_component/InvitationDashboard/InvitationList.tsx
  src/app/(afterLogin)/_component/InvitationDashboard/index.tsx
  src/app/(afterLogin)/_constant/type.ts
  src/app/(afterLogin)/_util/submitInvitation.ts
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/InviteList/index.tsx
  src/app/_hook/useRenderModal.tsx
Labels: Feat

#108 [#106] 기본 모달
  src/app/_component/modal/base/index.tsx
  src/app/_component/modal/index.tsx
  src/app/_component/modal/wrongPW/index.tsx
  src/app/_util/returnModal.tsx
Labels: Feat

#107 [#91] 로그인, 회원가입 요구사항 구현 및 전역 정보 처리
  src/app/(afterLogin)/_component/SideMenu/index.tsx
  src/app/(afterLogin)/myboard/page.tsx
  src/app/(beforeLogin)/_component/Auth/AuthLayout.tsx
  src/app/(beforeLogin)/_constants/type.ts
  src/app/(beforeLogin)/login/page.tsx
  src/app/(beforeLogin)/signup/page.tsx
  src/app/_api/users/index.tsx
  src/app/_component/Button/Sign/index.tsx
  src/app/_component/InputForm/PasswordCheck.tsx
  src/app/_component/InputForm/PasswrdInput.tsx
  src/app/_component/modal/ModalLayout.tsx
  src/app/_constant/Input.ts
  src/app/_hook/useRenderModal.tsx
  src/app/_recoil/AuthAtom/index.ts
  src/app/_recoil/ModalNameAtom/index.ts
  src/app/_recoil/dashboardAtom/index.ts
  src/app/_util/axiosInstance.tsx
Labels: Feat

#113 [#112] Recoil 새로고침 문제 Fix
  package-lock.json
  package.json
  src/app/_recoil/AuthAtom/index.ts
Labels: bug

#105 [#100] 대시보드 생성, 나의 대시보드 목록 페이지네이션
  src/app/(afterLogin)/_api/dashboard.ts
  src/app/(afterLogin)/_component/CardList/index.tsx
  src/app/(afterLogin)/_component/DashboardList/index.tsx
  src/app/(afterLogin)/_component/SideMenu/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/EditBoard/index.tsx
  src/app/(afterLogin)/layout.tsx
  src/app/(afterLogin)/myboard/page.tsx
  src/app/_api/Dashboards/index.ts
  src/app/_component/Button/CardDashboard/index.tsx
  src/app/_component/Button/Confirm/index.tsx
  src/app/_component/Chip/SelectColor/index.tsx
  src/app/_component/InputForm/InputStyle.tsx
  src/app/_component/InputForm/TextInput.tsx
  src/app/_component/InputForm/index.tsx
  src/app/_component/modal/dashBoard/index.tsx
  src/app/_constant/Input.ts
Labels: Feat

#114 [#98] 대시보드 정보 변경 , 대시보드 , 구성원 , 초대내역 ,삭제기능 구현
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/EditBoard/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/InviteList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/MemberList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/page.tsx
  src/app/_api/Dashboards/index.ts
  src/app/_component/Button/Confirm/index.tsx
  src/app/_recoil/dashboardAtom/index.ts
Labels: Feat

#117 [#110] 헤더 드롭다운 메뉴 구현, 로그인 에러 메시지 커스텀
  src/app/(afterLogin)/_component/Header/HeaderDropdown.tsx
  src/app/(afterLogin)/_component/Header/HeaderProfile.tsx
  src/app/(afterLogin)/_component/Header/index.tsx
  src/app/(beforeLogin)/_constants/type.ts
  src/app/(beforeLogin)/login/page.tsx
  src/app/_constant/type.ts
  src/app/_recoil/AuthAtom/index.ts
  src/app/_util/axiosInstance.tsx
  tailwind.config.ts
Labels: Feat
