Repository Codeit-Part3-Team3/Taskify, pull requests merged in 2024-01, with the labels that each got.

#124 [#109] 카드 무한 스크롤
  .eslintrc
  src/app/(afterLogin)/_component/Card/index.tsx
  src/app/(afterLogin)/_component/CardList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/page.tsx
  src/app/_component/modal/toDoCard/DetailComponent.tsx
  src/app/_component/modal/toDoCard/index.tsx
  src/app/_hook/useInfiniteScroll.tsx
  src/app/globals.css
  tsconfig.json
Labels: Feat

#127 [#122] Tag, Header 컴포넌트 리펙토링
  src/app/(afterLogin)/_component/Header/index.tsx
  src/app/_component/Chip/Tag/index.tsx
  src/app/_component/InputForm/TagInput.tsx
  src/app/_constant/Chip.ts
Labels: Refactor

#131 [#125] 전체 모달 스타일 수정
  .eslintrc
  package-lock.json
  package.json
  public/icons/line.svg
  src/app/(afterLogin)/_component/Card/index.tsx
  src/app/(afterLogin)/_component/CardList/index.tsx
  src/app/(afterLogin)/_component/DashboardList/index.tsx
  src/app/(afterLogin)/_component/InvitationDashboard/index.tsx
  src/app/(afterLogin)/_component/SideMenu/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/page.tsx
  src/app/_api/card/index.tsx
  src/app/_component/Button/Cancel/index.tsx
  src/app/_component/Button/Confirm/index.tsx
  src/app/_component/Chip/Tag/index.tsx
  src/app/_component/Input/InputField.tsx
  src/app/_component/InputForm/InputStyle.tsx
  src/app/_component/InputForm/TagInput.tsx
  src/app/_component/InputForm/index.tsx
  src/app/_component/dropdown/filter/index.tsx
  src/app/_component/dropdown/index.tsx
  src/app/_component/modal/ModalLayout.tsx
  src/app/_component/modal/column/index.tsx
  src/app/_component/modal/index.tsx
  src/app/_component/modal/toDoCard/DetailComponent.tsx
  src/app/_component/modal/toDoCard/index.tsx
  src/app/_hook/usePutCard.tsx
  src/app/_util/returnModal.tsx
  tailwind.config.ts
Labels: Feat

#128 [#119] /mypage, 모달 인풋 리팩토링
  src/app/(afterLogin)/_component/Card/index.tsx
  src/app/_component/Button/Confirm/index.tsx
  src/app/_component/InputForm/CommentInput.tsx
  src/app/_component/InputForm/DateInput.tsx
  src/app/_component/InputForm/InputStyle.tsx
  src/app/_component/InputForm/TagInput.tsx
  src/app/_component/InputForm/index.tsx
  src/app/_component/dropdown/filter/index.tsx
  src/app/_component/modal/column/index.tsx
  src/app/_component/modal/toDoCard/index.tsx
Labels: Refactor

#135 [#111] NotFound 페이지, 페이지 별 리다이렉트 처리, 리팩토링
  package-lock.json
  package.json
  public/images/notfound_image.png
  public/images/unauthorization_image.png
  src/app/(afterLogin)/_component/DashboardList/index.tsx
  src/app/(afterLogin)/_component/Header/index.tsx
  src/app/(afterLogin)/_util/submitInvitation.ts
  src/app/(afterLogin)/dashboard/[dashboardId]/page.tsx
  src/app/(afterLogin)/layout.tsx
  src/app/(afterLogin)/myboard/page.tsx
  src/app/(beforeLogin)/_component/Auth/AuthLayout.tsx
  src/app/(beforeLogin)/login/page.tsx
  src/app/(beforeLogin)/page.tsx
  src/app/(beforeLogin)/pageunauthorizated/page.tsx
  src/app/_component/NotFound/index.tsx
  src/app/_util/axiosHeader
  src/app/_util/axiosInstance.tsx
  src/app/_util/getAccessToken.tsx
  src/app/not-found.tsx
  tsconfig.json
Labels: Feat

#136 [#60] 프로필 수정
  src/app/(afterLogin)/_component/AddImageFile/index.tsx
  src/app/(afterLogin)/_component/AddImageFile/uploadImage.tsx
  src/app/(afterLogin)/_component/EditLayout/index.tsx
  src/app/(afterLogin)/_component/Header/index.tsx
  src/app/(afterLogin)/_component/SideMenu/index.tsx
  src/app/(afterLogin)/mypage/PasswordEdit/index.tsx
  src/app/(afterLogin)/mypage/ProfileEdit/index.tsx
  src/app/(afterLogin)/mypage/UserEditLayout/index.tsx
  src/app/(afterLogin)/mypage/page.tsx
  src/app/(beforeLogin)/_constants/type.ts
  src/app/_api/users/index.tsx
  src/app/_component/InputForm/index.tsx
  src/app/_constant/modalType.tsx
  src/app/_recoil/AuthAtom/index.ts
Labels: Feat

#140 [#137] feat: 헤더 대시보드 아이디 연결
  src/app/(afterLogin)/_component/Header/index.tsx
  src/app/(afterLogin)/_component/InvitationDashboard/DummyData.tsx
  src/app/(afterLogin)/_component/ProfileImgCollection/index.tsx
  src/app/(afterLogin)/_util/useGetMembers.ts
  src/app/_util/useAsync.ts
Labels: Feat

#130 [#126] 할 일 목록 카드 드래그 앤 드롭 기능 구현
  package-lock.json
  package.json
  src/app/(afterLogin)/_component/CardList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/page.tsx
  src/app/_hook/useDragEnd.ts
Labels: Feat

#145 [#143] Meta 데이터 , SEO
  src/app/_constant/Meta.ts
  src/app/layout.tsx
  src/app/robots.ts
  src/app/sitemap.ts
Labels: Feat

#150 [#147] ReadMe 작성
  README.md
  src/app/favicon.ico
Labels: Chore

#154 [#144] 헤더 QA 수정
  src/app/(afterLogin)/_component/AddImageFile/index.tsx
  src/app/(afterLogin)/_component/Header/HeaderDropdown.tsx
  src/app/(afterLogin)/_component/Header/HeaderProfile.tsx
  src/app/(afterLogin)/_component/Header/index.tsx
  src/app/(afterLogin)/_component/ProfileImgCollection/index.tsx
  src/app/(beforeLogin)/_constants/type.ts
  src/app/_constant/Input.ts
  src/app/_util/axiosHeader
Labels: Fix

#153 [#152] 스타일 수정
  src/app/(afterLogin)/_component/SideMenu/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/page.tsx
Labels: Refactor

#157 [#148] 컬럼, 할 일 상세 헤더 고정 및 스타일 오류 수정
  src/app/(afterLogin)/_component/AddImageFile/index.tsx
  src/app/(afterLogin)/_component/CardList/index.tsx
  src/app/(afterLogin)/_component/EditLayout/index.tsx
  src/app/(afterLogin)/_component/Header/index.tsx
  src/app/(afterLogin)/_component/SideMenu/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/EditBoard/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/InviteList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/MemberList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/page.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/page.tsx
  src/app/_component/Button/DeleteDashboard/index.tsx
  src/app/_component/modal/toDoCard/DetailComponent.tsx
  src/app/_component/modal/toDoCard/index.tsx
Labels: Feat

#163 [#162] 나의 대시보드 QA 수정
  src/app/(afterLogin)/_component/DashboardList/index.tsx
  src/app/(afterLogin)/_component/InvitationDashboard/InvitationList.tsx
  src/app/(afterLogin)/_component/InvitationDashboard/index.tsx
  src/app/(afterLogin)/myboard/page.tsx
Labels: Fix

#164 [#160] 로그아웃 후 메인페이지 이동시 API 오류 발생
  src/app/(afterLogin)/_component/ProfileImgCollection/index.tsx
Labels: bug

#169 [#161] 초대 내역 수정
  src/app/(afterLogin)/_component/Header/index.tsx
  src/app/(afterLogin)/_util/submitInvitation.ts
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/EditBoard/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/InviteList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/MemberList/index.tsx
  src/app/_api/Dashboards/index.ts
  src/app/_component/modal/dashBoard/index.tsx
  src/app/_constant/Input.ts
  src/app/_recoil/dashboardAtom/index.ts
Labels: bug

#172 [#170] 드래그 앤 드롭 영역이 보이도록 수정
  src/app/(afterLogin)/dashboard/[dashboardId]/page.tsx
Labels: Fix

#174 [#168] 스타일 QA 수정
  src/app/(afterLogin)/_component/Card/index.tsx
  src/app/(afterLogin)/_component/SideMenu/index.tsx
  src/app/_component/Button/CardDashboard/index.tsx
  src/app/_component/modal/column/index.tsx
  src/app/_constant/Input.ts
Labels: Refactor

#177 Bug/login 로그인 실패시 alert와 모달 겹치는 문제
  src/app/(beforeLogin)/login/page.tsx
  src/app/_recoil/AuthAtom/index.ts
Labels: bug

#183 [#182] QA 수정
  src/app/_component/InputForm/DateInput.tsx
  src/app/_component/modal/toDoCard/update/index.tsx
Labels: Fix

#185 [#184] feat: 다크모드 미구현 적용
  src/app/(afterLogin)/mypage/ProfileEdit/index.tsx
  src/app/(afterLogin)/mypage/UserEditLayout/index.tsx
Labels: Fix

#194 [#192] refactor : toast 기능 추가
  package-lock.json
  package.json
  src/app/(afterLogin)/_component/Header/HeaderDropdown.tsx
  src/app/(afterLogin)/_component/InvitationDashboard/index.tsx
  src/app/(afterLogin)/_component/SideMenu/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/EditBoard/index.tsx
  src/app/(afterLogin)/layout.tsx
  src/app/(afterLogin)/mypage/PasswordEdit/index.tsx
  src/app/(afterLogin)/mypage/ProfileEdit/index.tsx
Labels: Feat, Refactor

#196 [#188] refactor : API 공통 에러메세지 파싱 로직 수정
  src/app/_util/axiosErrors.tsx
  src/app/_util/axiosInstance.tsx
  src/app/_util/getErrorMessages.ts
Labels: Refactor

#198 [#191] 모바일 계정관리 페이지
  src/app/_component/InputForm/PasswordCheck.tsx
  src/app/_component/InputForm/PasswrdInput.tsx
Labels: Fix

#197 [#189] 카드 컴포넌트 css 수정
  src/app/(afterLogin)/_component/Card/index.tsx
Labels: Fix

#201 [#195] 수정 ,변경 ,삭제 이벤트 모달
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/EditBoard/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/InviteList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/MemberList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/edit/page.tsx
  src/app/_util/SelectAlert/index.tsx
Labels: Feat

#200 [#190] css 수정
  package-lock.json
  package.json
  src/app/(afterLogin)/_component/Icons/LeftArrowIcon.tsx
  src/app/(afterLogin)/_component/Icons/RightArrowIcon.tsx
  src/app/(afterLogin)/_component/SideMenu/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/_component/Card/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/_component/CardList/index.tsx
  src/app/(afterLogin)/dashboard/[dashboardId]/page.tsx
  src/app/(afterLogin)/dashboard/page.tsx
  src/app/(afterLogin)/myboard/_component/DashboardList/index.tsx
  src/app/(afterLogin)/myboard/_component/InvitationDashboard/InvitationList.tsx
  src/app/(afterLogin)/myboard/_component/InvitationDashboard/NoInvitation.tsx
  src/app/(afterLogin)/myboard/_component/InvitationDashboard/index.tsx
  src/app/(afterLogin)/myboard/page.tsx
  src/app/(afterLogin)/mypage/ProfileEdit/index.tsx
  src/app/_component/Icons/CalendarIcon.tsx
  src/app/_component/Input/InputField.tsx
  src/app/_component/InputForm/DateInput.tsx
  src/app/_component/modal/_component/modalLayout/index.tsx
  src/app/_component/modal/_component/modalMainContent/index.tsx
  src/app/_component/modal/todo/detail/_component/comment/index.tsx
  src/app/_component/modal/todo/detail/_component/iconButton/index.tsx
  src/app/_component/modal/todo/detail/index.tsx
  src/app/_hook/useDragEnd.ts
Labels: Refactor

#203 [#190] 사이드메뉴의 선택된 대시보드에 다크모드 배경 적용
  src/app/(afterLogin)/_component/SideMenu/index.tsx
Labels: Fix

#204 [#190] css 수정
  src/app/(afterLogin)/_component/SideMenu/index.tsx
Labels: Fix
